#version 450

layout (local_size_x = 16, local_size_y = 16) in;
layout (binding = 0, rgba8) uniform readonly image2D inputImage;
layout (binding = 1, rgba8) uniform writeonly image2D outputImage;

layout(push_constant) uniform constants {
    int type;
} PushConstants;

void main() {
	ivec2 idx = ivec2(gl_GlobalInvocationID.xy);

	vec4 pixel = imageLoad(inputImage, idx);
	
    vec4 outPixel = pixel.brga;

	imageStore(outputImage, idx, outPixel);
}
